import * as vscode from 'vscode';
import * as path from 'path';
import { MavenUtils } from './mavenUtils';
import { CacheManager } from './cacheManager';

export class PomEditorProvider implements vscode.CustomTextEditorProvider {
    
    // 使用统一的缓存管理器
    private cacheManager: CacheManager;

    constructor(private readonly context: vscode.ExtensionContext) {
        this.cacheManager = new CacheManager(context);
    }

    public async resolveCustomTextEditor(
        document: vscode.TextDocument,
        webviewPanel: vscode.WebviewPanel,
        _token: vscode.CancellationToken
    ): Promise<void> {
        // Setup initial content for the webview
        webviewPanel.webview.options = {
            enableScripts: true,
            localResourceRoots: [
                vscode.Uri.joinPath(this.context.extensionUri, 'media')
            ]
        };

        webviewPanel.webview.html = this.getHtmlForWebview(webviewPanel.webview, document);

        // Hook up event listeners
        this.setupWebviewMessageListener(webviewPanel, document);
        this.setupDocumentChangeListener(document, webviewPanel);
    }

    private getHtmlForWebview(webview: vscode.Webview, document: vscode.TextDocument): string {
        // Get the CSS and JS URIs
        const styleUri = webview.asWebviewUri(
            vscode.Uri.joinPath(this.context.extensionUri, 'media', 'style.css')
        );
        const scriptUri = webview.asWebviewUri(
            vscode.Uri.joinPath(this.context.extensionUri, 'media', 'main.js')
        );

        // Monaco Editor loader
        const monacoLoaderUri = webview.asWebviewUri(
            vscode.Uri.joinPath(this.context.extensionUri, 'media', 'monaco-loader.js')
        );

        // Use a nonce to only allow specific scripts to run
        const nonce = getNonce();

        const pomContent = document.getText();

        // Detect current theme
        const theme = vscode.window.activeColorTheme.kind === vscode.ColorThemeKind.Dark ? 'vscode-dark' : 'vscode-light';

        return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'unsafe-inline' https://cdn.jsdelivr.net; font-src ${webview.cspSource} https://cdn.jsdelivr.net; script-src 'nonce-${nonce}' https://cdn.jsdelivr.net;">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="${styleUri}" rel="stylesheet">
    <title>Maven POM Editor</title>
</head>
<body class="${theme}">
    <div class="editor-container">
        <div class="tab-bar">
            <button class="tab-button active" data-tab="raw-pom">Raw POM</button>
            <button class="tab-button" data-tab="effective-pom">Effective POM</button>
            <button class="tab-button" data-tab="dependency-hierarchy">Dependency Hierarchy</button>
        </div>
        
        <div class="tab-content-container">
            <div id="raw-pom" class="tab-content active">
                <div id="monaco-editor-container"></div>
            </div>
            
            <div id="effective-pom" class="tab-content">
            </div>
            
            <div id="dependency-hierarchy" class="tab-content">
            </div>
        </div>
    </div>
    
    <script nonce="${nonce}">
        const vscodeApi = acquireVsCodeApi();
        const initialContent = ${JSON.stringify(pomContent)};
    </script>
    <script nonce="${nonce}" src="${monacoLoaderUri}"></script>
    <script nonce="${nonce}" src="${scriptUri}"></script>
</body>
</html>`;
    }

    private setupWebviewMessageListener(
        webviewPanel: vscode.WebviewPanel,
        document: vscode.TextDocument
    ): void {
        webviewPanel.webview.onDidReceiveMessage(
            async (message) => {
                switch (message.type) {
                    case 'update':
                        await this.updateTextDocument(document, message.content);
                        break;
                    case 'log':
                        console.log('Webview:', message.content);
                        break;
                    case 'getEffectivePom':
                        await this.handleGetEffectivePom(webviewPanel, document, message.forceRefresh);
                        break;
                    case 'getDependencyTree':
                        await this.handleGetDependencyTree(webviewPanel, document, message.forceRefresh);
                        break;
                    case 'getResolvedDependencies':
                        await this.handleGetResolvedDependencies(webviewPanel, document, message.forceRefresh);
                        break;
    // source code generated by GenAI of Kiro starts
                    case 'openMvnRepository':
                        await this.handleOpenMvnRepository(
                            webviewPanel,
                            message.groupId,
                            message.artifactId
                        );
                        break;
                    // souce code generated by GenAI of Kiro ends
                }
            }
        );
    }

    private async handleGetEffectivePom(
        webviewPanel: vscode.WebviewPanel,
        document: vscode.TextDocument,
        forceRefresh: boolean = false
    ): Promise<void> {
        await this.executeWithProgress(
            webviewPanel,
            document,
            'effectivePom',
            forceRefresh,
            async (pomPath: string) => {
                // 步骤 1: 检查 Maven 环境 (10%)
                await this.reportProgress(webviewPanel, 'effectivePom', 1, '检查 Maven 环境');
                const mavenAvailable = await MavenUtils.isMavenAvailable();
                if (!mavenAvailable) {
                    throw new Error('Maven 未安装或未添加到 PATH 中。请安装 Maven 后重试。');
                }

                // 步骤 2: 解析依赖关系 (30%)
                await this.reportProgress(webviewPanel, 'effectivePom', 2, '解析依赖关系');
                
                // 步骤 3: 生成 Effective POM (60%)
                await this.reportProgress(webviewPanel, 'effectivePom', 3, '生成 Effective POM');
                const effectivePom = await MavenUtils.getEffectivePom(pomPath);

                // 步骤 4: 处理结果 (90%)
                await this.reportProgress(webviewPanel, 'effectivePom', 4, '处理结果');
                
                return effectivePom;
            }
        );
    }

    private async handleGetDependencyTree(
        webviewPanel: vscode.WebviewPanel,
        document: vscode.TextDocument,
        forceRefresh: boolean = false
    ): Promise<void> {
        await this.executeWithProgress(
            webviewPanel,
            document,
            'dependencyTree',
            forceRefresh,
            async (pomPath: string) => {
                // 步骤 1: 检查 Maven 环境 (10%)
                await this.reportProgress(webviewPanel, 'dependencyTree', 1, '检查 Maven 环境');
                const mavenAvailable = await MavenUtils.isMavenAvailable();
                if (!mavenAvailable) {
                    throw new Error('Maven 未安装或未添加到 PATH 中。请安装 Maven 后重试。');
                }

                // 步骤 2: 解析依赖关系 (30%)
                await this.reportProgress(webviewPanel, 'dependencyTree', 2, '解析依赖关系');
                
                // 步骤 3: 生成依赖树 (60%)
                await this.reportProgress(webviewPanel, 'dependencyTree', 3, '生成依赖树');
                const treeText = await MavenUtils.getDependencyTree(pomPath);

                // 步骤 4: 处理结果 (90%)
                await this.reportProgress(webviewPanel, 'dependencyTree', 4, '处理结果');
                const treeData = MavenUtils.parseDependencyTree(treeText);
                
                return treeData;
            }
        );
    }

    private async handleGetResolvedDependencies(
        webviewPanel: vscode.WebviewPanel,
        document: vscode.TextDocument,
        forceRefresh: boolean = false
    ): Promise<void> {
        await this.executeWithProgress(
            webviewPanel,
            document,
            'resolvedDependencies',
            forceRefresh,
            async (pomPath: string) => {
                // 步骤 1: 检查 Maven 环境 (10%)
                await this.reportProgress(webviewPanel, 'resolvedDependencies', 1, '检查 Maven 环境');
                const mavenAvailable = await MavenUtils.isMavenAvailable();
                if (!mavenAvailable) {
                    throw new Error('Maven 未安装或未添加到 PATH 中。请安装 Maven 后重试。');
                }

                // 步骤 2: 解析依赖关系 (30%)
                await this.reportProgress(webviewPanel, 'resolvedDependencies', 2, '解析依赖关系');
                
                // 步骤 3: 生成依赖列表 (60%)
                await this.reportProgress(webviewPanel, 'resolvedDependencies', 3, '生成依赖列表');
                const listText = await MavenUtils.getResolvedDependencies(pomPath);

                // 步骤 4: 处理结果 (90%)
                await this.reportProgress(webviewPanel, 'resolvedDependencies', 4, '处理结果');
                const dependencies = MavenUtils.parseResolvedDependencies(listText);
                
                return dependencies;
            }
        );
    }

    private setupDocumentChangeListener(
        document: vscode.TextDocument,
        webviewPanel: vscode.WebviewPanel
    ): void {
        const changeDocumentSubscription = vscode.workspace.onDidChangeTextDocument(e => {
            if (e.document.uri.toString() === document.uri.toString()) {
                // Document was changed externally, update the webview
                webviewPanel.webview.postMessage({
                    type: 'update',
                    content: document.getText()
                });
            }
        });

        // Clean up when webview is closed
        webviewPanel.onDidDispose(() => {
            changeDocumentSubscription.dispose();
        });
    }

    private async updateTextDocument(document: vscode.TextDocument, content: string): Promise<void> {
        const edit = new vscode.WorkspaceEdit();
        
        // Replace the entire document
        edit.replace(
            document.uri,
            new vscode.Range(0, 0, document.lineCount, 0),
            content
        );

        await vscode.workspace.applyEdit(edit);
    }

    /**
     * 执行带进度的操作
     * @param webviewPanel Webview 面板
     * @param document 文档
     * @param cacheKey 缓存键
     * @param forceRefresh 是否强制刷新
     * @param executor 执行函数
     */
    private async executeWithProgress<T>(
        webviewPanel: vscode.WebviewPanel,
        document: vscode.TextDocument,
        cacheKey: string,
        forceRefresh: boolean,
        executor: (pomPath: string) => Promise<T>
    ): Promise<void> {
        const messageType = this.getMessageType(cacheKey);
        
        try {
            // 显示加载状态
            this.showLoadingState(webviewPanel, cacheKey, true);

            const pomPath = document.uri.fsPath;

            // 检查缓存
            const cachedData = await this.cacheManager.get(pomPath, cacheKey, forceRefresh);
            if (cachedData) {
                console.log(`[PomEditor] 使用缓存的 ${cacheKey} 数据`);
                this.showCachedResult(webviewPanel, cacheKey, cachedData);
                return;
            }

            console.log(`[PomEditor] 从 Maven 获取 ${cacheKey}...`);

            // 执行操作
            const result = await executor(pomPath);

            // 缓存结果
            await this.cacheManager.set(pomPath, cacheKey, result);

            // 发送结果到 webview
            webviewPanel.webview.postMessage({
                type: `${messageType}Result`,
                [this.getResultKey(cacheKey)]: result,
                loading: false,
                fromCache: false
            });
        } catch (error: any) {
            console.error(`获取 ${cacheKey} 失败:`, error);
            this.showError(webviewPanel, cacheKey, error.message || `获取 ${cacheKey} 失败`);
        }
    }

    /**
     * 显示加载状态
     */
    private showLoadingState(webviewPanel: vscode.WebviewPanel, cacheKey: string, loading: boolean): void {
        const messageType = this.getMessageType(cacheKey);
        webviewPanel.webview.postMessage({
            type: `${messageType}Loading`,
            loading
        });
    }

    /**
     * 显示缓存结果
     */
    private showCachedResult(webviewPanel: vscode.WebviewPanel, cacheKey: string, data: any): void {
        const messageType = this.getMessageType(cacheKey);
        webviewPanel.webview.postMessage({
            type: `${messageType}Result`,
            [this.getResultKey(cacheKey)]: data,
            loading: false,
            fromCache: true
        });
    }

    /**
     * 显示错误
     */
    private showError(webviewPanel: vscode.WebviewPanel, cacheKey: string, error: string): void {
        const messageType = this.getMessageType(cacheKey);
        webviewPanel.webview.postMessage({
            type: `${messageType}Error`,
            error,
            loading: false
        });
    }

    /**
     * 报告进度
     */
    private async reportProgress(
        webviewPanel: vscode.WebviewPanel,
        cacheKey: string,
        step: number,
        message: string
    ): Promise<void> {
        const messageType = this.getMessageType(cacheKey);
        webviewPanel.webview.postMessage({
            type: `${messageType}Progress`,
            step,
            message,
            progress: step * 25 // 每步25%
        });
        
        // 短暂延迟，让UI有时间更新
        await new Promise(resolve => setTimeout(resolve, 100));
    }

    /**
     * 获取消息类型前缀
     */
    private getMessageType(cacheKey: string): string {
        switch (cacheKey) {
            case 'effectivePom':
                return 'effectivePom';
            case 'dependencyTree':
                return 'dependencyTree';
            case 'resolvedDependencies':
                return 'resolvedDependencies';
            default:
                return cacheKey;
        }
    }

    /**
     * 获取结果键名
     */
    private getResultKey(cacheKey: string): string {
        switch (cacheKey) {
            case 'effectivePom':
                return 'content';
            case 'dependencyTree':
            case 'resolvedDependencies':
                return 'data';
            default:
                return 'data';
        }
    }

    // source code generated by GenAI of Kiro starts
    /**
     * 从多个 Maven 仓库获取依赖版本列表并显示在 QuickPick 中
     */
    private async handleOpenMvnRepository(
        webviewPanel: vscode.WebviewPanel,
        groupId: string,
        artifactId: string
    ): Promise<void> {
        try {
            const versions = await vscode.window.withProgress(
                {
                    location: vscode.ProgressLocation.Notification,
                    title: `Fetching versions for ${groupId}:${artifactId}...`,
                    cancellable: false
                },
                async () => {
                    return await this.fetchAllRepoVersions(
                        groupId, artifactId
                    );
                }
            );

            if (versions.length === 0) {
                vscode.window.showWarningMessage(
                    `No versions found for ${groupId}:${artifactId}`
                );
                return;
            }

            const items: vscode.QuickPickItem[] = versions.map(
                (v, index) => ({
                    label: v.version,
                    description:
                        (index === 0 ? '(latest) ' : '') +
                        `[${v.source}]`,
                    detail: `Updated: ${v.timestamp}`
                })
            );

            const selected = await vscode.window.showQuickPick(items, {
                placeHolder: `Select version for ${groupId}:${artifactId}`,
                title: `${artifactId} - Available Versions (${versions.length})`,
                matchOnDescription: true,
                matchOnDetail: true
            });

            if (selected) {
                await vscode.env.clipboard.writeText(selected.label);
                vscode.window.showInformationMessage(
                    `Version ${selected.label} copied to clipboard`
                );
            }
        } catch (error: any) {
            console.error('Failed to fetch Maven versions:', error);
            vscode.window.showErrorMessage(
                `Failed to fetch versions: ${error.message}`
            );
        }
    }

    /**
     * 从所有配置的仓库获取版本，合并去重，按日期降序排列
     */
    private async fetchAllRepoVersions(
        groupId: string,
        artifactId: string
    ): Promise<Array<{
        version: string; timestamp: string; source: string
    }>> {
        const groupPath = groupId.replace(/\./g, '/');

        const repos = [
            {
                name: 'Maven Central',
                hostname: 'repo1.maven.org',
                path: `/maven2/${groupPath}/${artifactId}/`
            },
            {
                name: 'Atlassian',
                hostname: 'maven.artifacts.atlassian.com',
                path: `/${groupPath}/${artifactId}/`
            }
        ];

        const allResults = await Promise.allSettled(
            repos.map(repo =>
                this.fetchFromRepo(repo.hostname, repo.path, repo.name)
            )
        );

        // Merge results, deduplicate by version (keep first seen)
        const versionMap = new Map<string, {
            version: string; timestamp: string;
            source: string; date: Date
        }>();

        // Collect Atlassian versions that need date resolution
        const atlassianNoDates: Array<{
            version: string;
            groupPath: string;
            artifactId: string;
        }> = [];

        for (const result of allResults) {
            if (result.status === 'fulfilled') {
                for (const v of result.value) {
                    if (!versionMap.has(v.version)) {
                        versionMap.set(v.version, v);
                        // Track Atlassian versions with no date
                        if (v.source === 'Atlassian' &&
                            v.date.getTime() === 0) {
                            atlassianNoDates.push({
                                version: v.version,
                                groupPath,
                                artifactId
                            });
                        }
                    } else {
                        const existing = versionMap.get(v.version)!;
                        if (!existing.source.includes(v.source)) {
                            existing.source += `, ${v.source}`;
                        }
                    }
                }
            } else {
                console.warn(
                    'Repo fetch failed:', result.reason?.message
                );
            }
        }

        // Fetch dates for Atlassian versions via HEAD requests
        // Limit to 30 versions to avoid too many requests
        if (atlassianNoDates.length > 0) {
            const toFetch = atlassianNoDates.slice(0, 30);
            const dateResults = await Promise.allSettled(
                toFetch.map(v =>
                    this.fetchAtlassianVersionDate(
                        v.groupPath, v.artifactId, v.version
                    )
                )
            );
            for (let i = 0; i < dateResults.length; i++) {
                const dr = dateResults[i];
                if (dr.status === 'fulfilled' && dr.value) {
                    const entry = versionMap.get(toFetch[i].version);
                    if (entry) {
                        entry.date = dr.value;
                        entry.timestamp = dr.value
                            .toISOString()
                            .replace('T', ' ')
                            .substring(0, 16);
                    }
                }
            }
        }

        // Sort by date descending
        const merged = Array.from(versionMap.values());
        merged.sort((a, b) => b.date.getTime() - a.date.getTime());

        return merged.map(({ version, timestamp, source }) => ({
            version, timestamp, source
        }));
    }

    /**
     * 通过 HEAD 请求获取 Atlassian 仓库中某版本的发布日期
     * 请求 .pom 文件的 Last-Modified 头
     */
    private async fetchAtlassianVersionDate(
        groupPath: string,
        artifactId: string,
        version: string
    ): Promise<Date | null> {
        const https = await import('https');
        const pomFile = `${artifactId}-${version}.pom`;
        const pomPath =
            `/${groupPath}/${artifactId}/${version}/${pomFile}`;

        return new Promise((resolve) => {
            const req = https.request({
                hostname: 'maven.artifacts.atlassian.com',
                path: pomPath,
                method: 'HEAD',
                headers: {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36'
                }
            }, (res) => {
                const lastMod = res.headers['last-modified'];
                if (lastMod) {
                    resolve(new Date(lastMod));
                } else {
                    resolve(null);
                }
                res.resume(); // Drain response
            });

            req.on('error', () => resolve(null));
            req.setTimeout(5000, () => {
                req.destroy();
                resolve(null);
            });
            req.end();
        });
    }

    /**
     * 从单个仓库获取版本列表
     */
    private async fetchFromRepo(
        hostname: string,
        repoPath: string,
        repoName: string
    ): Promise<Array<{
        version: string; timestamp: string;
        source: string; date: Date
    }>> {
        const https = await import('https');

        const options = {
            hostname,
            path: repoPath,
            method: 'GET',
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36',
                'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
                'Accept-Language': 'en-US,en;q=0.9'
            }
        };

        return new Promise((resolve, reject) => {
            const request = https.request(options, (res) => {
                if (res.statusCode === 301 || res.statusCode === 302) {
                    const redirectUrl = res.headers.location;
                    if (redirectUrl) {
                        https.get(
                            redirectUrl,
                            { headers: options.headers },
                            (rRes) => {
                                this.handleRepoResponse(
                                    rRes, repoName, resolve, reject
                                );
                            }
                        ).on('error', reject);
                        return;
                    }
                }
                this.handleRepoResponse(
                    res, repoName, resolve, reject
                );
            });

            request.on('error', reject);
            request.setTimeout(15000, () => {
                request.destroy();
                reject(new Error(`${repoName}: Request timeout`));
            });
            request.end();
        });
    }

    /**
     * 处理仓库 HTTP 响应
     */
    private handleRepoResponse(
        res: any,
        repoName: string,
        resolve: (value: Array<{
            version: string; timestamp: string;
            source: string; date: Date
        }>) => void,
        reject: (reason: Error) => void
    ): void {
        let data = '';
        res.on('data', (chunk: Buffer) => {
            data += chunk.toString();
        });
        res.on('end', () => {
            try {
                if (res.statusCode === 404) {
                    resolve([]);
                    return;
                }
                if (res.statusCode !== 200) {
                    reject(new Error(
                        `${repoName} HTTP ${res.statusCode}`
                    ));
                    return;
                }
                const versions = this.parseRepoHtml(data, repoName);
                resolve(versions);
            } catch (e: any) {
                reject(new Error(
                    `${repoName}: parse error: ${e.message}`
                ));
            }
        });
        res.on('error', (err: Error) => reject(err));
    }

    /**
     * 解析仓库 HTML 目录列表
     * Supports both Maven Central (<a> tags with dates) and
     * Atlassian/Nexus (plain text listing without dates)
     */
    private parseRepoHtml(
        html: string,
        repoName: string
    ): Array<{
        version: string; timestamp: string;
        source: string; date: Date
    }> {
        const versions: Array<{
            version: string; timestamp: string;
            source: string; date: Date
        }> = [];

        // Pattern 1: Maven Central style
        // <a href="2.29.51/">2.29.51/</a>  2024-12-19 18:42
        const htmlRegex =
            /<a\s+href="([^"]+\/)"\s*[^>]*>[^<]+<\/a>\s+(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2})/g;

        let match;
        let foundHtmlDates = false;
        while ((match = htmlRegex.exec(html)) !== null) {
            const ver = match[1].replace(/\/$/, '');
            const dateStr = match[2];
            if (this.isVersionDir(ver)) {
                foundHtmlDates = true;
                const date = new Date(
                    dateStr.replace(' ', 'T') + ':00Z'
                );
                versions.push({
                    version: ver,
                    timestamp: dateStr,
                    source: repoName,
                    date
                });
            }
        }

        // Pattern 2: Atlassian/Nexus plain text style
        // version/                  -         -
        if (!foundHtmlDates) {
            // Try <a> tags without dates
            const linkRegex = /<a\s+href="([^"]+\/)"\s*[^>]*>[^<]+<\/a>/g;
            while ((match = linkRegex.exec(html)) !== null) {
                const ver = match[1].replace(/\/$/, '');
                if (this.isVersionDir(ver)) {
                    versions.push({
                        version: ver,
                        timestamp: 'N/A',
                        source: repoName,
                        date: new Date(0)
                    });
                }
            }

            // Try plain text lines: "version/  -  -"
            if (versions.length === 0) {
                const lines = html.split('\n');
                for (const line of lines) {
                    const textMatch = line.match(
                        /^\s*([^\s<>]+\/)\s+/
                    );
                    if (textMatch) {
                        const ver = textMatch[1].replace(/\/$/, '');
                        if (this.isVersionDir(ver)) {
                            versions.push({
                                version: ver,
                                timestamp: 'N/A',
                                source: repoName,
                                date: new Date(0)
                            });
                        }
                    }
                }
            }
        }

        // Sort by date descending (newest first)
        versions.sort((a, b) => b.date.getTime() - a.date.getTime());
        return versions;
    }

    /**
     * 判断目录名是否为版本号（排除元数据文件等）
     */
    private isVersionDir(name: string): boolean {
        if (!name || name === '..' || name === '.') {
            return false;
        }
        if (name.includes('.xml') || name.includes('.md5') ||
            name.includes('.sha') || name.includes('.asc') ||
            name.includes('.index') || name === 'maven-metadata') {
            return false;
        }
        // Version should start with a digit
        return /^\d/.test(name);
    }
    // source code generated by GenAI of Kiro ends
}

function getNonce(): string {
    let text = '';
    const possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    for (let i = 0; i < 32; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
}

function escapeHtml(text: string): string {
    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

